name: Build
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile
        run: mvn clean compile assembly:single
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aletheia
          include-hidden-files: true
          path: target/*.jar
